services:
  app:
    build: 
      context: ./db
      dockerfile: Dockerfile
     

  db:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: waimar
      MYSQL_DATABASE: employees
    
