version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      # Your app environment variables
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: waimar
      DB_NAME: employees

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: waimar
      MYSQL_DATABASE: employees
    command: --default-authentication-plugin=mysql_native_password
