services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: waimar
    
