services:
  app:
    build:
      context: ./Lab03/blob/master
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: waimar
      MYSQL_DATABASE: employees
    
