
name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Start services in detached mode
        run: docker compose -f ./docker-compose.yml up -d
      - name: Stop services
        run: docker compose down

