name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package
      - name: Set up Docker Compose
        uses: docker/setup-compose-action
      - name: Run services and wait
        run: docker compose -f ./docker-compose.yml up --abort-on-container-exit
        

